"""update_commit_model

Revision ID: f0730004746f
Revises: 737c891dc100
Create Date: 2026-02-11 02:13:43.689316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0730004746f'
down_revision: Union[str, None] = '737c891dc100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('commits', sa.Column('video_assets', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'commits', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_column('commits', 'video_assets')
    op.drop_column('commits', 'author_id')
    # ### end Alembic commands ###
